import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import music.MusicManager;
import music.MusicPlayer;
import music.MusicProperty;
import networking.P2PMusicStreaming;

import javax.sound.sampled.*;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class MusicPlayerDashboard implements ActionListener {
    private JFrame rootFrame;
    private JTabbedPane MusicPlayerFeature;
    private JPanel HomeTab;
    private JPanel LibraryTab;
    private JPanel SearchTab;
    private JPanel InfoTab;
    private JButton backButton;
    private JButton startButton;
    private JButton lyricsButton;
    private JButton stopButton;
    private JSlider volumeSlider;
    private JProgressBar musicProgressBar;
    private JTextArea MusicInfo;
    private JTextPane textPane1;
    private JTable libraryTable;
    private JPanel MusicPlayer;
    private JPanel Music;
    private JFormattedTextField HomePageText;
    private JButton SYNCButton;
    private JLabel SyncMessage;
    private JScrollPane LibraryScroll;
    private JEditorPane selectedMusicBox;
    private JPanel SelectedPanel;
    private JTextArea lyricsDisplay;
    private JEditorPane musicTime;
    private JButton SearchButton;
    private JTextField SearchText;
    private JFormattedTextField lyricsRealtimeText;
    private JLabel lyricsRealtimeLabel;
    private JFormattedTextField serverIP;
    private JButton P2PconnectButton;
    private JLabel serverLabel;
    private JLabel clientLabel;
    private JFormattedTextField clientIP;
    private JButton P2PSync;
    private JFormattedTextField LibraryLocationPath;
    private JButton downloadBtn;
    private JLabel downloadPath;
    private JFormattedTextField ClientName;
    private JEditorPane ConnectTCPMessage;

    private DefaultTableModel LibraryTableModel;

    private Clip clip;
    private MusicPlayer player;

    public String csvPath = "./music_properties.csv";
    private MusicManager musicManager;
    public String AlbumPath = "./src/Album";
    public String userName = "Client1";
    public String serverIPaddress = "tcp://localhost:4444"; // default server address
    public String clientIPaddress = "tcp://localhost:5555"; // default client address
    private CompletableFuture lastConnectionTask;


    public ArrayList<String> TCPIP = new ArrayList<String>();


    public String getTcpIP() {
        return "\nserverIP: " + TCPIP.get(0) + "\nclientIP: " + TCPIP.get(1);
    }

    public void setTcpIP(String serverIP, String clientIP) {
        TCPIP.clear();
        TCPIP.add(serverIP);
        TCPIP.add(clientIP);
    }


    public MusicManager getMusicManager() {
        if (musicManager == null) {
            musicManager = new MusicManager();
        }
        return musicManager;
    }

    public void setMusicManager(MusicManager musicManager) {
        this.musicManager = musicManager;
    }

    public void syncMusicInfo() { // get the music management
        musicManager.reload(AlbumPath);
        System.out.println(AlbumPath);
        musicManager.saveMusicPropertyToFile(csvPath);
        System.out.println(csvPath);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        MusicPlayer = new JPanel();
        MusicPlayer.setLayout(new GridBagLayout());
        MusicPlayerFeature = new JTabbedPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 5;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        MusicPlayer.add(MusicPlayerFeature, gbc);
        HomeTab = new JPanel();
        HomeTab.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        MusicPlayerFeature.addTab("Home", HomeTab);
        HomePageText = new JFormattedTextField();
        HomePageText.setText("This is CSCI33280 Project");
        HomeTab.add(HomePageText);
        Music = new JPanel();
        Music.setLayout(new GridBagLayout());
        MusicPlayerFeature.addTab("Music", Music);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        Music.add(scrollPane1, gbc);
        lyricsDisplay.setEditable(false);
        lyricsDisplay.setText("");
        scrollPane1.setViewportView(lyricsDisplay);
        lyricsRealtimeText = new JFormattedTextField();
        lyricsRealtimeText.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Music.add(lyricsRealtimeText, gbc);
        lyricsRealtimeLabel = new JLabel();
        lyricsRealtimeLabel.setText("Lryics realtime:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        Music.add(lyricsRealtimeLabel, gbc);
        LibraryTab = new JPanel();
        LibraryTab.setLayout(new BorderLayout(0, 0));
        MusicPlayerFeature.addTab("Library", LibraryTab);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        LibraryTab.add(panel1, BorderLayout.SOUTH);
        SyncMessage = new JLabel();
        SyncMessage.setEnabled(true);
        SyncMessage.setText("Can't see your Song? Library Path:");
        panel1.add(SyncMessage, BorderLayout.WEST);
        SYNCButton.setText("SYNC!");
        panel1.add(SYNCButton, BorderLayout.EAST);
        P2PSync.setText("P2PSycn");
        panel1.add(P2PSync, BorderLayout.NORTH);
        LibraryLocationPath.setText("./src/ClientMusic/client1");
        panel1.add(LibraryLocationPath, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.SOUTH);
        downloadPath = new JLabel();
        downloadPath.setText("Download Path:");
        panel2.add(downloadPath, BorderLayout.WEST);
        ClientName.setText("./src/ClientMusic/client1/");
        panel2.add(ClientName, BorderLayout.CENTER);
        downloadBtn = new JButton();
        downloadBtn.setText("DOWNLOAD!");
        panel2.add(downloadBtn, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        LibraryTab.add(panel3, BorderLayout.NORTH);
        SearchText.setEditable(true);
        SearchText.setEnabled(true);
        SearchText.setText("Search Here");
        panel3.add(SearchText, BorderLayout.CENTER);
        SearchButton.setText("Search!");
        panel3.add(SearchButton, BorderLayout.EAST);
        LibraryScroll = new JScrollPane();
        LibraryTab.add(LibraryScroll, BorderLayout.CENTER);
        LibraryScroll.setViewportView(libraryTable);
        SearchTab = new JPanel();
        SearchTab.setLayout(new GridBagLayout());
        MusicPlayerFeature.addTab("Search", SearchTab);
        textPane1 = new JTextPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        SearchTab.add(textPane1, gbc);
        InfoTab = new JPanel();
        InfoTab.setLayout(new GridBagLayout());
        MusicPlayerFeature.addTab("Info", InfoTab);
        MusicInfo = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        InfoTab.add(MusicInfo, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        MusicPlayerFeature.addTab("P2P", panel4);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel4.add(panel5, BorderLayout.CENTER);
        serverIP.setText("tcp://localhost:4444");
        panel5.add(serverIP, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel5.add(spacer1, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        serverLabel = new JLabel();
        serverLabel.setText("Server:");
        panel5.add(serverLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        clientLabel = new JLabel();
        clientLabel.setText("Client:");
        panel5.add(clientLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        clientIP.setText("tcp://localhost:5555");
        panel5.add(clientIP, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        P2PconnectButton.setText("Connect!");
        panel5.add(P2PconnectButton, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel5.add(ConnectTCPMessage, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        musicProgressBar = new JProgressBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(musicProgressBar, gbc);
        SelectedPanel = new JPanel();
        SelectedPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 5;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        MusicPlayer.add(SelectedPanel, gbc);
        musicTime = new JEditorPane();
        musicTime.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        SelectedPanel.add(musicTime, gbc);
        selectedMusicBox.setEditable(false);
        selectedMusicBox.setText("You Have Not Select Any Music");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.8;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 0, 0);
        SelectedPanel.add(selectedMusicBox, gbc);
        backButton = new JButton();
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(backButton, gbc);
        startButton = new JButton();
        startButton.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(startButton, gbc);
        lyricsButton.setText("Lryics");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(lyricsButton, gbc);
        volumeSlider = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(volumeSlider, gbc);
        stopButton = new JButton();
        stopButton.setText("Stop");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MusicPlayer.add(stopButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MusicPlayer;
    }

    class TargetMusic {
        public MusicProperty property;
        public String title;
        public String Path;
        public String author;
        public float duration;

        public String tcpClient;
    }


    public TargetMusic targetMusic = new TargetMusic();

    public void setTargetMusic(TargetMusic targetMusic) {
        targetMusic.Path = targetMusic.Path.substring(targetMusic.Path.indexOf("src"));
        this.targetMusic = targetMusic;
    }

    public void loadLibraryTableFromSearch(ArrayList<MusicProperty> musicProperties) {
        LibraryTableModel.setRowCount(0);
        musicManager.setMusicInfo(musicProperties);
        for (MusicProperty musicProperty : musicProperties) {
            LibraryTableModel.addRow(new Object[]{
                    musicProperty.title,
                    musicProperty.duration,
                    musicProperty.artist,
                    musicProperty.channels,
                    musicProperty.rate,
                    musicProperty.bits,
                    musicProperty.album,
                    musicProperty.genre,
                    musicProperty.year,
                    musicProperty.comment,
                    musicProperty.ftpPath
            });
        }

    }

    public void loadLibraryTable() {
        LibraryTableModel.setRowCount(0);
        for (MusicProperty musicProperty : musicManager.getMusicInfo()) {
            LibraryTableModel.addRow(new Object[]{
                    musicProperty.title,
                    musicProperty.duration,
                    musicProperty.artist,
                    musicProperty.channels,
                    musicProperty.rate,
                    musicProperty.bits,
                    musicProperty.album,
                    musicProperty.genre,
                    musicProperty.year,
                    musicProperty.comment,
                    !musicProperty.ftpPath.equals(clientIPaddress) ? musicProperty.ftpPath : ""
            });
        }
    }

    public P2PMusicStreaming app = null;

    public void setApp(P2PMusicStreaming app) {
        this.app = app;
    }

    public P2PMusicStreaming getApp() {
        return app;
    }

    public LrcFileReader.LrcLine getLrcLine(int ms) throws IOException { // get the lrc line
        String lrcPath = targetMusic.Path.replace(".wav", ".lrc");
        if (targetMusic.property == null || !targetMusic.property.hasLrc)
            return null;

        LrcFileReader reader = new LrcFileReader(lrcPath);

        LrcFileReader.LrcLine prevLine = null;

        for (LrcFileReader.LrcLine line : reader.getLrcLines()) {
            if (line.getTimestamp() > ms) {
                return prevLine;
            }
            prevLine = line;
        }
        return null;
    }

    public void getLrcLines() throws IOException { // get the lrc lines
        lyricsDisplay.setText("");

        String lrcPath = targetMusic.Path.replace(".wav", ".lrc");

        LrcFileReader reader = new LrcFileReader(lrcPath);

        String lrc = "";
        for (LrcFileReader.LrcLine line : reader.getLrcLines()) {
            System.out.println(line.getTimestamp() + " " + line.getLyrics());
            lrc += " " + line.getLyrics() + "\n";
        }
        lyricsDisplay.setText(lrc);
    }

    public String getFormattedTimeMs(int ms) {
        int min = ms / 1000 / 60;
        int sec = ms / 1000 % 60;
        return String.format("%d:%02d", min, sec);
    }

    public void setVolume() {
        player.setVolume((float) volumeSlider.getValue() / volumeSlider.getMaximum());
    }

    public boolean isMusicLocal(TargetMusic music) {
        return music.tcpClient == null || music.tcpClient.isEmpty() || clientIPaddress.equals(music.tcpClient);
    }

    public MusicPlayerDashboard() {

    }

    private void init() {
       

        rootFrame = new JFrame("MusicPlayerDashboard");
        rootFrame.setContentPane(this.MusicPlayer);
        rootFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        rootFrame.pack();
        rootFrame.setVisible(true);

        startButton.addActionListener(this);
        stopButton.addActionListener(this);

        volumeSlider.addChangeListener(e -> {
            setVolume();
        });

        player = new MusicPlayer(this::getApp);
    }

    @Override
    public void actionPerformed(ActionEvent event) {
        if (event.getSource() == startButton) {
            try {

                if (player.isPlaying()) {
                    player.stop();
                }

                player.startPlayMusic(targetMusic.property, isMusicLocal(targetMusic));

                // Set the maximum value of the progress bar to the length of the audio file
                musicProgressBar.setMaximum((int) targetMusic.duration);

                // Create a SwingWorker to play the audio and update the progress bar in the
                // background
                SwingWorker<Void, Integer> worker = new SwingWorker<>() {

                    @Override
                    protected Void doInBackground() throws Exception {
                        System.out.println("latestPosition");
                        boolean oncePlayed = false;
                        while (player.isOpen()) {
                            if (oncePlayed && !player.isPlaying())
                                break;
                            if (!oncePlayed && player.isPlaying())
                                oncePlayed = true;
                            int position = (int) player.getCurrentTime();
                            publish(position); // publish the position to update the progress bar on the EDT
                            Thread.sleep(1000);
                        }
                        return null;
                    }

                    @Override
                    protected void process(List<Integer> chunks) {
                        // Update the progress bar on the EDT;
                        int latestPosition = chunks.get(chunks.size() - 1);
                        musicProgressBar.setValue(latestPosition);
                        String endTime = getFormattedTimeMs((int) targetMusic.duration * 1000);
                        String startTime = getFormattedTimeMs(latestPosition * 1000);
                        musicTime.setText(startTime + " / " + endTime);
                        System.out.println("SwingWorker, process(): " + latestPosition);
                        if (latestPosition < 1) {
                            //clear last song realtime lrc
                            lyricsRealtimeText.setText("");
                        }

                        try {
                            LrcFileReader.LrcLine lrcLine = getLrcLine(latestPosition * 1000);
                            if (lrcLine != null) {
                                lyricsRealtimeText.setText(lrcLine.getLyrics());
                            }
                        } catch (IOException e) {
                            e.printStackTrace();
                            lyricsRealtimeText.setText("NONE! no lrc file");
                        }

                    }
                };

                worker.execute(); // start the SwingWorker

            } catch (Exception e) {
                e.printStackTrace();
                selectedMusicBox.setText("NONE! no music in the list (information Display)");
            }
        } else if (event.getSource() == stopButton) {
            player.stop();
            player.close();
            musicProgressBar.setValue(0);
            musicTime.setText("0:00 / 0:00");
        }
    }

    public static void main(String[] args) {
        MusicPlayerDashboard player = new MusicPlayerDashboard();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            if (player.getApp() != null) {
                CompletableFuture.runAsync(() -> player.getApp().unregisterWithTracker());
            }
        }));
        player.init();
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        // create the lyricsButton
        lyricsButton = new JButton("Lyrics");
        lyricsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MusicPlayerFeature.setSelectedIndex(1); // switch to the Music tab
            }
        });
        // create lyricsButton end

        // create the table model
        libraryTable = new JTable();
        LibraryTableModel = new DefaultTableModel();
        LibraryTableModel.addColumn("Title");
        LibraryTableModel.addColumn("Duration");
        LibraryTableModel.addColumn("Author");
        LibraryTableModel.addColumn("Channels");
        LibraryTableModel.addColumn("Rate");
        LibraryTableModel.addColumn("Bits");
        LibraryTableModel.addColumn("Album");
        LibraryTableModel.addColumn("Genre");
        LibraryTableModel.addColumn("Year");
        LibraryTableModel.addColumn("Comment");
        LibraryTableModel.addColumn("TCP");
        getMusicManager().loadFromCsv(csvPath);
        loadLibraryTable();
        libraryTable.setModel(LibraryTableModel);

        // add a selection listener to the table
        selectedMusicBox = new JEditorPane(); // assuming you have a JEditorPane instance
        libraryTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                // check if the selection is valid and not adjusting
                if (!event.getValueIsAdjusting() && libraryTable.getSelectedRow() != -1) {
                    // get the selected row data
                    Object selectedData = libraryTable.getValueAt(libraryTable.getSelectedRow(), 0); // assuming the
                    // data is in the
                    // first column

                    TargetMusic targetMusic = new TargetMusic();
                    MusicProperty selectedProperty = getMusicManager().getMusicInfo()
                            .get(libraryTable.getSelectedRow());
                    targetMusic.property = selectedProperty;
                    targetMusic.title = selectedProperty.title;
                    targetMusic.duration = selectedProperty.duration;
                    targetMusic.author = selectedProperty.artist;
                    targetMusic.Path = selectedProperty.path;
                    targetMusic.tcpClient = selectedProperty.ftpPath;
                    System.out.println("tcp is " + targetMusic.tcpClient);
                    System.out.println("clientIPaddress is " + clientIPaddress);
                    if (!MusicPlayerDashboard.this.isMusicLocal(targetMusic)) {
                        System.out.println("tcp is null");

                        setTargetMusic(targetMusic);
                        // set the selected data to the JEditorPane
                        selectedMusicBox.setText(targetMusic.title + " (" + targetMusic.Path + ") "
                                + (targetMusic.author.isBlank() ? "(No Authors)" : targetMusic.author) + " (non local music)");
//                        selectedMusicBox.setText(targetMusic.title +"NONE! this is not your local music (information Display)");


                    } else {
                        setTargetMusic(targetMusic);
                        // set the selected data to the JEditorPane
                        selectedMusicBox.setText(targetMusic.title + " (" + targetMusic.Path + ") "
                                + (targetMusic.author.isBlank() ? "(No Authors)" : targetMusic.author));

                        try {
                            System.out.println("get lrc lines");
                            getLrcLines();
                        } catch (IOException e) {
                            lyricsDisplay.setText("No Lyrics");
                        }
                    }
                }
            }
        });

        LibraryLocationPath = new JFormattedTextField();
        /*LibraryLocationPath.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("LibraryLocationPath");
                String path = LibraryLocationPath.getText();
                AlbumPath = path;
                System.out.println(AlbumPath);
            }
        });*/

        ClientName = new JFormattedTextField();
        ClientName.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("ClientName");
                String name = ClientName.getText();
                userName = name;
                System.out.println(userName);
                csvPath = AlbumPath + "/" + userName + ".csv";
                System.out.println("csvPath: " + csvPath);
            }
        });

        LibraryScroll = new JScrollPane(libraryTable);
        // create the table model end
        SYNCButton = new JButton("SYNC");
        SYNCButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("SYNC...");
                String path = LibraryLocationPath.getText();
                AlbumPath = path;
                System.out.println("LibraryLocationPath: " + AlbumPath);
                syncMusicInfo();
                loadLibraryTable();

            }
        });

        lyricsDisplay = new JTextArea();
        lyricsDisplay.setText("lyricsDisplay");
        lyricsDisplay.setEditable(false);

        SearchButton = new JButton("Search");
        SearchText = new JTextField("Search Here");

        SearchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String searchText = SearchText.getText();
                TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(libraryTable.getModel());
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
                libraryTable.setRowSorter(sorter);
            }
        });

        serverIP = new JFormattedTextField();
        serverIP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTcpIP(serverIP.getText(), clientIP.getText());
                ConnectTCPMessage.setText("Connecting to " + getTcpIP() + "...");
            }
        });
        /*serverIP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("serverIP");
                String ip = serverIP.getText();
                serverIPaddress = ip;
                System.out.println("serverIPaddress: "+ serverIPaddress);
            }
        });*/

        clientIP = new JFormattedTextField();
        clientIP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setTcpIP(serverIP.getText(), clientIP.getText());
                ConnectTCPMessage.setText("Connecting to " + getTcpIP() + "...");
            }
        });
        /*clientIP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("clientIP");
                String ip = clientIP.getText();
                clientIPaddress = ip;
                System.out.println("clientIPaddress: "+ clientIPaddress);
            }
        });*/

        P2PconnectButton = new JButton("P2Pconnect");
        P2PconnectButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (lastConnectionTask != null && !lastConnectionTask.isDone()) {
                    System.out.println("Still connecting!");
                    return;
                }
                String serverip = serverIP.getText();
                serverIPaddress = serverip;
                System.out.println("serverIP: " + serverIPaddress);
                String clientip = clientIP.getText();
                clientIPaddress = clientip;
                System.out.println("clinetIP: " + clientIPaddress);
                System.out.println("P2Pconnect");

                if (!serverIPaddress.isEmpty() && !clientIPaddress.isEmpty()) {
                    if (MusicPlayerDashboard.this.app != null) {
                        MusicPlayerDashboard.this.app.close();
                        MusicPlayerDashboard.this.app = null;
                    }
                    P2PMusicStreaming app = null;
                    try {
                        app = P2PMusicStreaming.run(serverIPaddress, clientIPaddress);
                        setApp(app);
                        syncMusicInfo();
                        app.setMusicManager(getMusicManager());
                    } catch (RuntimeException ex) {
                        JOptionPane.showMessageDialog(rootFrame, "cannot connect to tracker server");
                    }
                } else {
                    System.out.println("IP is null");
                }
            }
        });

        P2PSync = new JButton("P2PSync");
        P2PSync.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("P2PSync");

                P2PMusicStreaming app = getApp();
                List<String> onlinePeers = app.getOnlinePeers(serverIPaddress);
                System.out.println("onlinePeers: " + onlinePeers);


                HashSet<MusicProperty> peerMusicSet = new HashSet<>();
                for (String peer : onlinePeers) {
                    System.out.println("peer: " + peer);
                    ArrayList<MusicProperty> recvMusicList = app.sendSearchRequest("Na", peer);
                    System.out.println("recvMusicList: " + recvMusicList);
                    // Use addAll method to add received music properties to the HashSet
                    peerMusicSet.addAll(recvMusicList);
                }
                ArrayList<MusicProperty> peerMusicLists = new ArrayList<MusicProperty>(peerMusicSet);



                /*
                // Initialize peerMusicLists outside the loop
                ArrayList<MusicProperty> peerMusicLists = new ArrayList<MusicProperty>();

                for (String peer : onlinePeers) {
                    System.out.println("peer: " + peer);
                    ArrayList<MusicProperty> recvMusicList = app.sendSearchRequest("Na", peer);
                    System.out.println("recvMusicList: " + recvMusicList);
                    peerMusicLists.addAll(recvMusicList);
                }
                */

                System.out.println("peerMusicLists: output");
                for (MusicProperty music : peerMusicLists) {
                    System.out.println(music.title);
                }
                musicManager.setMusicInfo(peerMusicLists);
                loadLibraryTable();
//                loadLibraryTableFromSearch(peerMusicLists);

            }
        });

        ConnectTCPMessage = new JTextPane();

    }
}
